#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    # enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction = "left"
    autocomplete_method = "coc"

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell' default_position = 'bottom'
default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]
    cpp = ["clangd"]

[[layers]]
  name = "format"

[[layers]]
  name = "git"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = "checkers"
  enable = false

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[custom_plugins]]
   repo = 'liuchengxu/vim-clap'
   merged = false

[[custom_plugins]]
   repo = 'liuchengxu/vista.vim'
   merged = false

[[custom_plugins]]
   repo = 'pechorin/any-jump.vim'
   merged = false

[[custom_plugins]]
   repo = 'jreybert/vimagit'
   merged = false
