#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "jellybeans"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    # enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    default_indent = 4
    relativenumber = false
    enable_vimfiler_welcome = false
    filetree_direction = "left"
    enable_neomake = false
    enable_cursorcolumn = true
    checkinstall = false
    disabled_plugins = ["tabular", "vim-matchup", "open-browser.vim", "vim-table-mode"]
    autocomplete_method = "coc"
    # snippet_engine = "ultisnips"
    
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  # auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "checkers"
  enable = false

[[layers]]
  name = "core#tabline"
  enable = false

[[layers]]
  name = "core#statusline"
  enable = false

[[layers]]
  name = "core#banner"
  enable = false

[[layers]]
  name = "format"
  enable = false

[[layers]]
  name = "ui"
  enable = false

[[layers]]
  name = "lsp"
  filetypes = [
	'c',
	'cpp',
  ]
  [layers.override_cmd]
	 c = ['ccls', '--log-file=/tmp/ccls.log']
	 cpp = ['ccls', '--log-file=/tmp/ccls.log']

[[layers]]
  name = "sudo"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[custom_plugins]]
  repo = 'liuchengxu/vim-clap'
  merged = false
